### ISSUE TITLE
unabel to install the cvplot libarary on ubuntu machine. python 3.8. 

### ISSUE THREAD

**Issue by rajeshkalakoti** [iamDecode/cvplot#1]
```
Building wheels for collected packages: cvplot
  Building wheel for cvplot (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /ceph/home/rkalak/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpfe_6x7q2
       cwd: /tmp/pip-install-jq8jg8xq/cvplot_f9c234336165431bb09c92f47ebe4ab3
  Complete output (41 lines):
  setup.py entered
  $PATH=/tmp/pip-build-env-4cat893b/overlay/bin:/tmp/pip-build-env-4cat893b/normal/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/share/slurm/bin:/usr/share/slurm/sbin:/ceph/home/rkalak/.local/bin:/ceph/home/rkalak/bin
  running bdist_wheel
  running jsdeps
  `npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo
  Traceback (most recent call last):
    File "/ceph/home/rkalak/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/ceph/home/rkalak/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/ceph/home/rkalak/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-4cat893b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-4cat893b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-4cat893b/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 82, in <module>
      setup(**setup_args)
    File "/tmp/pip-build-env-4cat893b/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-4cat893b/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 503, in run
      [self.run_command(cmd) for cmd in cmds]
    File "/tmp/pip-build-env-4cat893b/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 503, in <listcomp>
      [self.run_command(cmd) for cmd in cmds]
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-4cat893b/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 274, in run
      c.run()
    File "/tmp/pip-build-env-4cat893b/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 401, in run
      raise ValueError(('missing files: %s' % missing))
  ValueError: missing files: ['/tmp/pip-install-jq8jg8xq/cvplot_f9c234336165431bb09c92f47ebe4ab3/js/dist/index.js']
  ----------------------------------------
  ERROR: Failed building wheel for cvplot
Failed to build cvplot
ERROR: Could not build wheels for cvplot, which is required to install pyproject.toml-based projects
Note: you may need to restart the kernel to use updated packages.
```

**Comment by iamDecode** [comment]
Thanks for the report! I have just released a new version (0.0.2), could you try again? You can make sure you install the new version by running: 

```
pip install cvplot==0.0.2
```


If you use jupyter lab, also run:

```
$ jupyter labextension install cvplot
```

and for classic jupyter notebooks, run:

```
jupyter nbextension install --py --symlink --overwrite --sys-prefix cvplot
jupyter nbextension enable --py --sys-prefix cvplot
```

---

If this still doesn't work, try installing `npm`, which you can do on ubuntu with the command 
```
sudo apt install nodejs npm
```
and try again.

Let me know if it works!

**Comment by rajeshkalakoti** [comment]
thanks for the reply, 
it's not working. this is npm packages error.  I am using jupyter notebook on a hpc cetre. I don't have permissions to install packages with sudo.  i can instally only pip packages.  
```py
Building wheels for collected packages: cvplot
  Building wheel for cvplot (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /ceph/home/rkalak/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpllt6jedw
       cwd: /tmp/pip-install-w3cqcyc1/cvplot_f4a4755525a74f05aa4445d19673a89c
  Complete output (41 lines):
  setup.py entered
  $PATH=/tmp/pip-build-env-9tab95d_/overlay/bin:/tmp/pip-build-env-9tab95d_/normal/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/share/slurm/bin:/usr/share/slurm/sbin:/ceph/home/rkalak/.local/bin:/ceph/home/rkalak/bin
  running bdist_wheel
  running jsdeps
  `yarn` unavailable.  If you're running this command using sudo, make sure `yarn` is available to sudo
  Traceback (most recent call last):
    File "/ceph/home/rkalak/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/ceph/home/rkalak/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/ceph/home/rkalak/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-9tab95d_/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-9tab95d_/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-9tab95d_/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 88, in <module>
      setup(**setup_args)
    File "/tmp/pip-build-env-9tab95d_/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-9tab95d_/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 503, in run
      [self.run_command(cmd) for cmd in cmds]
    File "/tmp/pip-build-env-9tab95d_/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 503, in <listcomp>
      [self.run_command(cmd) for cmd in cmds]
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-9tab95d_/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 274, in run
      c.run()
    File "/tmp/pip-build-env-9tab95d_/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 401, in run
      raise ValueError(('missing files: %s' % missing))
  ValueError: missing files: ['/tmp/pip-install-w3cqcyc1/cvplot_f4a4755525a74f05aa4445d19673a89c/js/dist/index.js']
  ----------------------------------------
  ERROR: Failed building wheel for cvplot
Failed to build cvplot
ERROR: Could not build wheels for cvplot, which is required to install pyproject.toml-based projects
Note: you may need to restart the kernel to use updated packages.
```

**Comment by iamDecode** [comment]
Ah this is similar to the first error, so maybe try also installing `yarn` (follow for instance [this guide](https://linuxize.com/post/how-to-install-yarn-on-ubuntu-20-04/))? In the meantime I will have a look to see if it is possible to remove the requirement of npm and yarn from the setup.

**Comment by rajeshkalakoti** [comment]
thank you.

**Comment by rajeshkalakoti** [comment]
hello, Could you please give some examples to plot the feature cv plots for the interpretatio?

**Comment by iamDecode** [comment]
Check out the example notebook `Example.ipynb` in the repository

**Comment by rajeshkalakoti** [comment]
I did, but  I tested your code. but there are no plots i am getting.

**Comment by rajeshkalakoti** [comment]
how to draw the plots for the each feature.

**Comment by iamDecode** [comment]
You have to provide me with a little bit more information. Want do you see? Is there an error? Which jupyter are you using (notebook / lab, version)? Which version? Did you follow the instructions in the readme, and also ran

(for jupyter lab)
```
jupyter labextension install cvplot
```

(for jupyter notebook)
```
jupyter nbextension install --py --symlink --overwrite --sys-prefix cvplot
jupyter nbextension enable --py --sys-prefix cvplot
```

If no error, can you share the output in the developer console/web inspector?
